---
version: "3.8"

services:
  adguard:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8088:80
    volumes:
      - ~/Adguard/conf:/opt/adguardhome/conf
      - ~/Adguard/work:/opt/adguardhome/work
    networks:
      - host

networks:
  host: